#!/usr/bin/env bash

set -e
# set -x

echo 'Setup venv'
python3 -m venv /workspaces/.venv
source /workspaces/.venv/bin/activate
pip install -U pip
pip install setuptools

echo 'Install esphome'
pip install esphome

# echo 'Clone esphome for cpp reference'
# git clone --depth=1 https://github.com/esphome/esphome.git /workspaces/esphome

cpp_json=.vscode/c_cpp_properties.json
if [ ! -f $cpp_json ]; then
    echo "Initializing PlatformIO..."
    pio init --ide vscode --silent
    sed -i "/\\/workspaces\/esphome-victron_ble\/include/d" $cpp_json
    sed -i "s/\"\/workspaces\/esphome-victron_ble\"/\"\/workspaces\/.venv\/lib\/python3.11\/site-packages\/\"/" $cpp_json
else
    echo "Cpp environment already configured. To reconfigure it you can run one the following commands:"
    echo "  pio init --ide vscode"
fi

# echo 'Run first build for victron_ble_connect - devcontainer-victron_ble_connect-compile'
# script/devcontainer-victron_ble_connect-compile

# echo 'Run first build for victron_ble - devcontainer-victron_ble-compile'
# script/devcontainer-victron_ble-compile