#!/usr/bin/env bash

set -e
# set -x

echo 'Setup venv'
python3 -m venv /workspaces/.venv
source /workspaces/.venv/bin/activate
pip install -U pip

echo 'Install esphome'
pip install esphome

echo 'Run first build for victron_ble_connect - devcontainer-victron_ble_connect-compile'
script/devcontainer-victron_ble_connect-compile

echo 'Run first build for victron_ble - devcontainer-victron_ble-compile'
script/devcontainer-victron_ble-compile